INFO : 2021-03-14 23:40:45,032 : This is working for Protection1!
INFO : 2021-03-14 23:40:45,050 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-14 23:40:45,080 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-14 23:40:45,084 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-14 23:40:45,085 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 42, in calc
    df_list = objProtection1.getOutputProtection2()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 80, in getOutputProtection2
    self.exposureArray=[self.rawData.getStateExposureTable().iloc[1,3],self.rawData.getStateExposureTable().iloc[1,3],
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 22, in getStateExposureTable
    self.stateExposureTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../static/state_exposure_data.csv'
INFO : 2021-03-14 23:40:45,100 : 127.0.0.1 - - [14/Mar/2021 23:40:45] "[35m[1mGET /modelcalc?protection=2 HTTP/1.1[0m" 500 -
INFO : 2021-03-14 23:40:45,238 : 127.0.0.1 - - [14/Mar/2021 23:40:45] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:56:23,156 : This is working for Protection1!
INFO : 2021-03-14 23:56:23,173 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-14 23:56:23,205 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-14 23:56:23,206 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-14 23:56:23,743 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-14 23:56:23,747 : Protection 1 Output Generated Successfully!
INFO : 2021-03-14 23:56:23,750 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-14 23:56:23,760 : 127.0.0.1 - - [14/Mar/2021 23:56:23] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:56:23,900 : 127.0.0.1 - - [14/Mar/2021 23:56:23] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:27,551 : Just an information for Protection 2
INFO : 2021-03-14 23:57:27,552 : This is working for Protection1!
INFO : 2021-03-14 23:57:27,569 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-14 23:57:27,598 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-14 23:57:27,599 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-14 23:57:27,752 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-14 23:57:27,760 : Protection 1 Output Generated Successfully!
INFO : 2021-03-14 23:57:27,764 : 127.0.0.1 - - [14/Mar/2021 23:57:27] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:27,980 : 127.0.0.1 - - [14/Mar/2021 23:57:27] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:30,739 : Just an information for Protection 2
INFO : 2021-03-14 23:57:30,741 : This is working for Protection1!
INFO : 2021-03-14 23:57:30,759 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-14 23:57:30,785 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-14 23:57:30,787 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-14 23:57:30,879 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-14 23:57:30,882 : Protection 1 Output Generated Successfully!
INFO : 2021-03-14 23:57:30,884 : 127.0.0.1 - - [14/Mar/2021 23:57:30] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:31,011 : 127.0.0.1 - - [14/Mar/2021 23:57:31] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:31,182 : Just an information for Protection 2
INFO : 2021-03-14 23:57:31,182 : This is working for Protection1!
INFO : 2021-03-14 23:57:31,206 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-14 23:57:31,268 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-14 23:57:31,270 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-14 23:57:31,337 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-14 23:57:31,341 : Protection 1 Output Generated Successfully!
INFO : 2021-03-14 23:57:31,345 : 127.0.0.1 - - [14/Mar/2021 23:57:31] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:31,465 : 127.0.0.1 - - [14/Mar/2021 23:57:31] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:32,059 : Just an information for Protection 2
INFO : 2021-03-14 23:57:32,060 : This is working for Protection1!
INFO : 2021-03-14 23:57:32,078 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-14 23:57:32,097 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-14 23:57:32,099 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-14 23:57:32,173 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-14 23:57:32,176 : Protection 1 Output Generated Successfully!
INFO : 2021-03-14 23:57:32,179 : 127.0.0.1 - - [14/Mar/2021 23:57:32] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:32,295 : 127.0.0.1 - - [14/Mar/2021 23:57:32] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:32,930 : Just an information for Protection 2
INFO : 2021-03-14 23:57:32,931 : This is working for Protection1!
INFO : 2021-03-14 23:57:32,953 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-14 23:57:32,989 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-14 23:57:32,990 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-14 23:57:33,054 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-14 23:57:33,057 : Protection 1 Output Generated Successfully!
INFO : 2021-03-14 23:57:33,059 : 127.0.0.1 - - [14/Mar/2021 23:57:33] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-14 23:57:33,178 : 127.0.0.1 - - [14/Mar/2021 23:57:33] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:06,706 : This is working for Protection1!
INFO : 2021-03-15 00:01:06,725 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:01:06,761 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:01:06,763 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:01:06,836 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:01:06,839 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:01:06,842 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-15 00:01:06,851 : 127.0.0.1 - - [15/Mar/2021 00:01:06] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:07,016 : 127.0.0.1 - - [15/Mar/2021 00:01:07] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:20,035 : Just an information for Protection 2
INFO : 2021-03-15 00:01:20,035 : This is working for Protection1!
INFO : 2021-03-15 00:01:20,053 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:01:20,084 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:01:20,085 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:01:20,160 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:01:20,162 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:01:20,164 : 127.0.0.1 - - [15/Mar/2021 00:01:20] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:20,295 : 127.0.0.1 - - [15/Mar/2021 00:01:20] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:20,953 : Just an information for Protection 2
INFO : 2021-03-15 00:01:20,954 : This is working for Protection1!
INFO : 2021-03-15 00:01:20,972 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:01:21,011 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:01:21,014 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:01:21,081 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:01:21,084 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:01:21,087 : 127.0.0.1 - - [15/Mar/2021 00:01:21] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:21,209 : 127.0.0.1 - - [15/Mar/2021 00:01:21] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:25,188 : Just an information for Protection 1
INFO : 2021-03-15 00:01:25,189 : This is working for Protection1!
INFO : 2021-03-15 00:01:25,206 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:01:25,256 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:01:25,258 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:01:25,863 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:01:25,866 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:01:25,868 : 127.0.0.1 - - [15/Mar/2021 00:01:25] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:26,020 : 127.0.0.1 - - [15/Mar/2021 00:01:26] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:34,925 : Just an information for Protection 1
INFO : 2021-03-15 00:01:34,928 : This is working for Protection1!
INFO : 2021-03-15 00:01:34,959 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:01:35,030 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:01:35,032 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:01:35,602 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:01:35,604 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:01:35,606 : 127.0.0.1 - - [15/Mar/2021 00:01:35] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:01:35,923 : 127.0.0.1 - - [15/Mar/2021 00:01:35] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:02:12,650 : This is working for Protection1!
INFO : 2021-03-15 00:02:12,667 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:02:12,717 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:02:12,718 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:02:13,261 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:02:13,264 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:02:13,267 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-15 00:02:13,276 : 127.0.0.1 - - [15/Mar/2021 00:02:13] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:02:13,408 : 127.0.0.1 - - [15/Mar/2021 00:02:13] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:02:18,005 : Just an information for Protection 1
INFO : 2021-03-15 00:02:18,007 : This is working for Protection1!
INFO : 2021-03-15 00:02:18,024 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:02:18,071 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:02:18,073 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:02:18,833 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:02:18,836 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:02:18,838 : 127.0.0.1 - - [15/Mar/2021 00:02:18] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:02:18,966 : 127.0.0.1 - - [15/Mar/2021 00:02:18] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:02:22,130 : Just an information for Protection 2
INFO : 2021-03-15 00:02:22,131 : This is working for Protection1!
INFO : 2021-03-15 00:02:22,149 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:02:22,178 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:02:22,179 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:02:22,267 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:02:22,270 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:02:22,272 : 127.0.0.1 - - [15/Mar/2021 00:02:22] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:02:22,353 : 127.0.0.1 - - [15/Mar/2021 00:02:22] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:03:44,004 : This is working for Protection1!
INFO : 2021-03-15 00:03:44,025 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:03:44,067 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:03:44,068 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:03:44,134 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:03:44,139 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:03:44,142 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-15 00:03:44,152 : 127.0.0.1 - - [15/Mar/2021 00:03:44] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:03:44,229 : 127.0.0.1 - - [15/Mar/2021 00:03:44] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:03:46,426 : Just an information for Protection 1
INFO : 2021-03-15 00:03:46,427 : This is working for Protection1!
INFO : 2021-03-15 00:03:46,445 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:03:46,492 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:03:46,494 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:03:47,096 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:03:47,101 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:03:47,104 : 127.0.0.1 - - [15/Mar/2021 00:03:47] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:03:47,181 : 127.0.0.1 - - [15/Mar/2021 00:03:47] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:29:28,844 : This is working for Protection1!
INFO : 2021-03-15 00:29:28,861 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:29:28,890 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:29:28,892 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:29:29,417 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:29:29,420 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:29:29,423 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-15 00:29:29,433 : 127.0.0.1 - - [15/Mar/2021 00:29:29] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:29:29,662 : 127.0.0.1 - - [15/Mar/2021 00:29:29] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:29:33,979 : Just an information for Protection 1
INFO : 2021-03-15 00:29:33,982 : This is working for Protection1!
INFO : 2021-03-15 00:29:33,997 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:29:34,017 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:29:34,019 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:29:34,530 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:29:34,533 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:29:34,535 : 127.0.0.1 - - [15/Mar/2021 00:29:34] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:29:34,660 : 127.0.0.1 - - [15/Mar/2021 00:29:34] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:29:37,705 : Just an information for Protection 2
INFO : 2021-03-15 00:29:37,714 : This is working for Protection1!
INFO : 2021-03-15 00:29:37,759 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:29:37,790 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:29:37,791 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:29:37,886 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:29:37,891 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:29:37,895 : 127.0.0.1 - - [15/Mar/2021 00:29:37] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:29:38,085 : 127.0.0.1 - - [15/Mar/2021 00:29:38] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:51:56,248 : This is working for Protection1!
INFO : 2021-03-15 00:51:56,264 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 00:51:56,290 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 00:51:56,292 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 00:51:56,765 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 00:51:56,770 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 00:51:56,775 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-15 00:51:56,794 : 127.0.0.1 - - [15/Mar/2021 00:51:56] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 00:51:57,043 : 127.0.0.1 - - [15/Mar/2021 00:51:57] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:41:43,196 : This is working for Protection1!
INFO : 2021-03-15 13:41:43,500 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 13:41:43,545 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 13:41:43,546 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 13:41:44,020 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 13:41:44,023 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 13:41:44,047 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-15 13:41:44,057 : 127.0.0.1 - - [15/Mar/2021 13:41:44] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:41:44,235 : 127.0.0.1 - - [15/Mar/2021 13:41:44] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:41:46,439 : Just an information for Protection 2
INFO : 2021-03-15 13:41:46,442 : This is working for Protection1!
INFO : 2021-03-15 13:41:46,472 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 13:41:46,499 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 13:41:46,500 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-15 13:41:46,628 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-15 13:41:46,634 : Protection 1 Output Generated Successfully!
INFO : 2021-03-15 13:41:46,636 : 127.0.0.1 - - [15/Mar/2021 13:41:46] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:41:46,790 : 127.0.0.1 - - [15/Mar/2021 13:41:46] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:43:05,686 : This is working for Protection1!
INFO : 2021-03-15 13:43:05,703 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 13:43:05,726 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 13:43:05,726 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-15 13:43:05,726 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 42, in calc
    df_list = objProtection1.getOutputProtection2()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 80, in getOutputProtection2
    self.exposureArray=[self.rawData.getStateExposureTable().iloc[1,3],self.rawData.getStateExposureTable().iloc[1,3],
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 21, in getStateExposureTable
    self.stateExposureTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\state_exposure_data.csv'
INFO : 2021-03-15 13:43:05,771 : 127.0.0.1 - - [15/Mar/2021 13:43:05] "[35m[1mGET /modelcalc?protection=2 HTTP/1.1[0m" 500 -
INFO : 2021-03-15 13:43:05,906 : 127.0.0.1 - - [15/Mar/2021 13:43:05] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:43:07,154 : Just an information for Protection 2
INFO : 2021-03-15 13:43:07,154 : This is working for Protection1!
INFO : 2021-03-15 13:43:07,169 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 13:43:07,192 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 13:43:07,192 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-15 13:43:07,192 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 42, in calc
    df_list = objProtection1.getOutputProtection2()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 80, in getOutputProtection2
    self.exposureArray=[self.rawData.getStateExposureTable().iloc[1,3],self.rawData.getStateExposureTable().iloc[1,3],
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 21, in getStateExposureTable
    self.stateExposureTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\state_exposure_data.csv'
INFO : 2021-03-15 13:43:07,194 : 127.0.0.1 - - [15/Mar/2021 13:43:07] "[35m[1mGET /modelcalc?protection=2 HTTP/1.1[0m" 500 -
INFO : 2021-03-15 13:43:07,299 : 127.0.0.1 - - [15/Mar/2021 13:43:07] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:43:08,914 : Just an information for Protection 2
INFO : 2021-03-15 13:43:08,917 : This is working for Protection1!
INFO : 2021-03-15 13:43:08,932 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 13:43:08,957 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 13:43:08,957 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-15 13:43:08,959 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 42, in calc
    df_list = objProtection1.getOutputProtection2()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 80, in getOutputProtection2
    self.exposureArray=[self.rawData.getStateExposureTable().iloc[1,3],self.rawData.getStateExposureTable().iloc[1,3],
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 21, in getStateExposureTable
    self.stateExposureTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\state_exposure_data.csv'
INFO : 2021-03-15 13:43:08,967 : 127.0.0.1 - - [15/Mar/2021 13:43:08] "[35m[1mGET /modelcalc?protection=2 HTTP/1.1[0m" 500 -
INFO : 2021-03-15 13:43:09,057 : 127.0.0.1 - - [15/Mar/2021 13:43:09] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:43:10,884 : Just an information for Protection 2
INFO : 2021-03-15 13:43:10,889 : This is working for Protection1!
INFO : 2021-03-15 13:43:10,912 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 13:43:10,947 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 13:43:10,949 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-15 13:43:10,949 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 42, in calc
    df_list = objProtection1.getOutputProtection2()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 80, in getOutputProtection2
    self.exposureArray=[self.rawData.getStateExposureTable().iloc[1,3],self.rawData.getStateExposureTable().iloc[1,3],
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 21, in getStateExposureTable
    self.stateExposureTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\state_exposure_data.csv'
INFO : 2021-03-15 13:43:10,952 : 127.0.0.1 - - [15/Mar/2021 13:43:10] "[35m[1mGET /modelcalc?protection=2 HTTP/1.1[0m" 500 -
INFO : 2021-03-15 13:43:11,043 : 127.0.0.1 - - [15/Mar/2021 13:43:11] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:43:12,329 : 127.0.0.1 - - [15/Mar/2021 13:43:12] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-15 13:43:13,989 : Just an information for Protection 1
INFO : 2021-03-15 13:43:13,991 : This is working for Protection1!
INFO : 2021-03-15 13:43:14,006 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-15 13:43:14,032 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-15 13:43:14,033 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-15 13:43:14,033 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 33, in calc
    df_list = objProtection1.getOutputProtection1()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 42, in getOutputProtection1
    self.exposureArray = [self.getWeightValue("Vehicle1","Violation"),self.getWeightValue("Vehicle1","Violation"),
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 97, in getWeightValue
    return (((self.rawData.getVehicleTypeWeightTable().loc[(self.rawData.getVehicleTypeWeightTable()['Vehicle Class'] == vehicleClass) &
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 47, in getVehicleTypeWeightTable
    self.vctable = self.getVehicleClassTable()
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 29, in getVehicleClassTable
    self.vehicleClassTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\vehicle_class_data.csv'
INFO : 2021-03-15 13:43:14,037 : 127.0.0.1 - - [15/Mar/2021 13:43:14] "[35m[1mGET /modelcalc?protection=1 HTTP/1.1[0m" 500 -
INFO : 2021-03-15 13:43:14,171 : 127.0.0.1 - - [15/Mar/2021 13:43:14] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 15:50:27,298 : This is working for Protection1!
INFO : 2021-03-16 15:50:27,326 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 15:50:27,419 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 15:50:27,421 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-16 15:50:27,422 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 33, in calc
    df_list = objProtection1.getOutputProtection1()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 42, in getOutputProtection1
    self.exposureArray = [self.getWeightValue("Vehicle1","Violation"),self.getWeightValue("Vehicle1","Violation"),
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 97, in getWeightValue
    return (((self.rawData.getVehicleTypeWeightTable().loc[(self.rawData.getVehicleTypeWeightTable()['Vehicle Class'] == vehicleClass) &
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 47, in getVehicleTypeWeightTable
    self.vctable = self.getVehicleClassTable()
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 29, in getVehicleClassTable
    self.vehicleClassTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\vehicle_class_data.csv'
INFO : 2021-03-16 15:50:27,455 : 127.0.0.1 - - [16/Mar/2021 15:50:27] "[35m[1mGET /modelcalc?protection=1 HTTP/1.1[0m" 500 -
INFO : 2021-03-16 15:50:27,764 : 127.0.0.1 - - [16/Mar/2021 15:50:27] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 15:50:29,355 : Just an information for Protection 1
INFO : 2021-03-16 15:50:29,356 : This is working for Protection1!
INFO : 2021-03-16 15:50:29,372 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 15:50:29,413 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 15:50:29,414 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-16 15:50:29,415 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 33, in calc
    df_list = objProtection1.getOutputProtection1()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 42, in getOutputProtection1
    self.exposureArray = [self.getWeightValue("Vehicle1","Violation"),self.getWeightValue("Vehicle1","Violation"),
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 97, in getWeightValue
    return (((self.rawData.getVehicleTypeWeightTable().loc[(self.rawData.getVehicleTypeWeightTable()['Vehicle Class'] == vehicleClass) &
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 47, in getVehicleTypeWeightTable
    self.vctable = self.getVehicleClassTable()
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 29, in getVehicleClassTable
    self.vehicleClassTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\vehicle_class_data.csv'
INFO : 2021-03-16 15:50:29,418 : 127.0.0.1 - - [16/Mar/2021 15:50:29] "[35m[1mGET /modelcalc?protection=1 HTTP/1.1[0m" 500 -
INFO : 2021-03-16 15:50:29,514 : 127.0.0.1 - - [16/Mar/2021 15:50:29] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 15:51:53,033 : This is working for Protection1!
INFO : 2021-03-16 15:51:53,055 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 15:51:53,081 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 15:51:53,083 : Intermediate Table 3 Generated Successfully!
ERROR : 2021-03-16 15:51:53,083 : Exception on /modelcalc [GET]
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shivam\Desktop\poc_python\app.py", line 42, in calc
    df_list = objProtection1.getOutputProtection2()
  File "C:\Users\Shivam\Desktop\poc_python\Protections.py", line 80, in getOutputProtection2
    self.exposureArray=[self.rawData.getStateExposureTable().iloc[1,3],self.rawData.getStateExposureTable().iloc[1,3],
  File "C:\Users\Shivam\Desktop\poc_python\file\Functions.py", line 21, in getStateExposureTable
    self.stateExposureTable = pds.DataFrame(pds.read_csv(file))
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Shivam\Desktop\poc_python\env\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '..\\static\\state_exposure_data.csv'
INFO : 2021-03-16 15:51:53,092 : 127.0.0.1 - - [16/Mar/2021 15:51:53] "[35m[1mGET /modelcalc?protection=2 HTTP/1.1[0m" 500 -
INFO : 2021-03-16 15:51:53,228 : 127.0.0.1 - - [16/Mar/2021 15:51:53] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 15:54:23,172 : This is working for Protection1!
INFO : 2021-03-16 15:54:23,193 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 15:54:23,216 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 15:54:23,218 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 15:54:23,277 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 15:54:23,280 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 15:54:23,282 : Locating template "record.html":
    1: trying loader of application "app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Shivam\Desktop\poc_python\templates
       -> found ('C:\\Users\\Shivam\\Desktop\\poc_python\\templates\\record.html')
INFO : 2021-03-16 15:54:23,293 : 127.0.0.1 - - [16/Mar/2021 15:54:23] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 15:54:23,485 : 127.0.0.1 - - [16/Mar/2021 15:54:23] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 15:54:30,707 : Just an information for Protection 1
INFO : 2021-03-16 15:54:30,709 : This is working for Protection1!
INFO : 2021-03-16 15:54:30,723 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 15:54:30,766 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 15:54:30,767 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 15:54:31,255 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 15:54:31,258 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 15:54:31,260 : 127.0.0.1 - - [16/Mar/2021 15:54:31] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 15:54:31,399 : 127.0.0.1 - - [16/Mar/2021 15:54:31] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:03:24,807 : Just an information for Protection 1
INFO : 2021-03-16 16:03:24,808 : This is working for Protection1!
INFO : 2021-03-16 16:03:24,820 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 16:03:24,842 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 16:03:24,844 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 16:03:25,298 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 16:03:25,301 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 16:03:25,303 : 127.0.0.1 - - [16/Mar/2021 16:03:25] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:03:25,451 : 127.0.0.1 - - [16/Mar/2021 16:03:25] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:03:30,095 : Just an information for Protection 2
INFO : 2021-03-16 16:03:30,096 : This is working for Protection1!
INFO : 2021-03-16 16:03:30,117 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 16:03:30,154 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 16:03:30,156 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 16:03:30,255 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 16:03:30,260 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 16:03:30,263 : 127.0.0.1 - - [16/Mar/2021 16:03:30] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:03:30,412 : 127.0.0.1 - - [16/Mar/2021 16:03:30] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:03:41,628 : Just an information for Protection 1
INFO : 2021-03-16 16:03:41,630 : This is working for Protection1!
INFO : 2021-03-16 16:03:41,659 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 16:03:41,701 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 16:03:41,702 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 16:03:42,282 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 16:03:42,286 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 16:03:42,288 : 127.0.0.1 - - [16/Mar/2021 16:03:42] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:03:42,442 : 127.0.0.1 - - [16/Mar/2021 16:03:42] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:20:44,604 : Just an information for Protection 1
INFO : 2021-03-16 16:20:44,604 : This is working for Protection1!
INFO : 2021-03-16 16:20:44,621 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 16:20:44,644 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 16:20:44,645 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 16:20:45,160 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 16:20:45,163 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 16:20:45,166 : 127.0.0.1 - - [16/Mar/2021 16:20:45] "[37mGET /modelcalc?protection=1 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:20:45,307 : 127.0.0.1 - - [16/Mar/2021 16:20:45] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:20:47,498 : Just an information for Protection 2
INFO : 2021-03-16 16:20:47,515 : This is working for Protection1!
INFO : 2021-03-16 16:20:47,535 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 16:20:47,564 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 16:20:47,566 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 16:20:47,658 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 16:20:47,660 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 16:20:47,663 : 127.0.0.1 - - [16/Mar/2021 16:20:47] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:20:47,813 : 127.0.0.1 - - [16/Mar/2021 16:20:47] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:26:58,871 : Just an information for Protection 2
INFO : 2021-03-16 16:26:58,872 : This is working for Protection1!
INFO : 2021-03-16 16:26:58,893 : Intermediate Table 1 Generated Successfully!
INFO : 2021-03-16 16:26:58,912 : Intermediate Table 2 Generated Successfully!
INFO : 2021-03-16 16:26:58,913 : Intermediate Table 3 Generated Successfully!
INFO : 2021-03-16 16:26:58,973 : Intermediate Table 4 Generated Successfully!
INFO : 2021-03-16 16:26:58,977 : Protection 1 Output Generated Successfully!
INFO : 2021-03-16 16:26:58,980 : 127.0.0.1 - - [16/Mar/2021 16:26:58] "[37mGET /modelcalc?protection=2 HTTP/1.1[0m" 200 -
INFO : 2021-03-16 16:26:59,087 : 127.0.0.1 - - [16/Mar/2021 16:26:59] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
